### ISSUE TITLE
have json rpc client and server in the same package

### ISSUE THREAD

**Issue by nicola-lunghi** [bcb/jsonrpcserver#103]
Hi,
would be nice for testing to have both the jsonrpcclient and jsonrpcserver in the same package.
The client is useful for example to generate request objects

```
import ayncio
from jsonrpc.server import method, async_dispatch as dispatch
from jsonrpc.client.requests import Request

@method
async def ping(name):
    return f"name: {name}"

async def handle(request):
    return await dispatch(request)

def main():
    my_req = str(Request("ping", name="pippo"))
    result = await TestRpc.handle(my_req)
    print(result)

asyncio.run(main())
```

Also could help to uniform the API between the tweo modules (the Request object has the same name but is totally different)

**Comment by bcb** [comment]
Just install both packages.
