### ISSUE TITLE
Add debug parameter to custom-raised exceptions

### ISSUE THREAD

**Issue by bcb** [bcb/jsonrpcserver#110]
When raising a jsonrpcserver exception inside a method (such as InvalidParamsError or ApiError), pass `debug=True` to override the global `debug` setting and include the `data` attribute in response.

```python
if some_condition:
    raise InvalidParamsError("Age must be within the range 0-120", debug=True)
```
Responds with this, regardless of global debug value:
```json
{"jsonrpc": "2.0", "error": {"code": -32602, "message": "Invalid parameters", "data": "Age must be within the range 0-120"}, "id": 1}
```

Same goes for ApiError.

**Comment by bcb** [comment]
@steinymity we should favour this instead of forcing debug=True on ApiError

**Comment by bcb** [comment]
or maybe `safe=True`

**Comment by steinymity** [comment]
Well, for InvalidParamsError it is helpful to have the extra `data` field, but not strictly necessary. However, for ApiError the `data` parameter is more or less what this exception is all about: sending custom data. 

Or seen from a different perspective: If an internal server error occurs, I don't want to send `data` in production as it might contain sensitive data, however, I usually want to send the ApiError's `data` as this is something I explicitly state to be sent (there is no "accidental momentum" here as when I just made a programming error leading to an internal error).

However, I also see the point that this makes the `debug` parameter a bit inconsistent.

**Comment by bcb** [comment]
Yeah it’s mainly about the consistency of `debug`.

Without debug you’ll still get the `code` and `message` in the response.

**Comment by steinymity** [comment]
What about refactoring the entire `debug` setting? We could accept "legacy" values `True` and `False` and offer new enum values selecting the exact behavior of what is being send. This would put this choice into the hands of the user.

**Comment by bcb** [comment]
Yeah I think you might be right.

Maybe even a list of error `code`s which should include the data param.

**Comment by steinymity** [comment]
Or — to propose a functional element — we could allow users to specify a filter function that edits the message right before sending. We could offer some default implementations which remove `data` always/never/sometimes.

**Comment by bcb** [comment]
That would work for the explicitly raised exceptions (

**Comment by steinymity** [comment]
It would also work for the others if we make it a general filter function that is called for every error response after creating a subclass of `ErrorResponse`, e.g. in `handle_exceptions()`.

**Comment by bcb** [comment]
Definitely should look at all options.

Maybe we just forget `debug` and just don’t include any sensitive information in `data`.

**Comment by steinymity** [comment]
Yeah, this is indeed maybe the most reasonable way. If any server method fails in an unanticipated way (i.e., with any other exceptions than those defined by us), it is definitely a problem on the server side (e.g., insufficient sanity check of arguments), so there is actually no reason to send such exceptions' messages on the wire.

**Comment by bcb** [comment]
Yep, agreed.

I’ll create a new issue to remove debug.

**Comment by steinymity** [comment]
Yeah, this is indeed maybe the most reasonable way. If any server method fails in an unanticipated way (i.e., with any other exceptions than those defined by us), it is definitely a problem on the server side (e.g., insufficient sanity check of arguments), so there is actually no reason to send such exceptions' messages on the wire.

**Comment by MasterGroosha** [comment]
According to [JSON-RPC specification](https://www.jsonrpc.org/specification#error_object) "data" field is valid and may be used. In this case, I don't see any reasons to restrict the appearance of this field to `debug=True` setting.

**Comment by bcb** [comment]
It’s valid, but since there are two params (message and data) the original idea was for message to include a simple error message and data to include information you may not always want to disclose, such as paths on the server. Controlled with a debug flag.

Anyway, the decision is already made to remove the debug param.
