### ISSUE TITLE
Please include tests folder in the release tarball on PyPI

### ISSUE THREAD

**Issue by prusnak** [bcb/jsonrpcserver#124]
It seems you are not including the tests folder in the release tarball. This makes it impossible to run the tests when the package is installed via PyPI and one needs to checkout the sources from GitHub.

**Comment by bcb** [comment]
Hi @prusnak 

Going by the official packaging guide, it doesn’t include tests in the distribution. http://packaging.python.org/tutorials/packaging-projects/

Can you expand on why we would run the tests from the package installed via pypi? I would expect the tests have already passed before the distribution package was created.

**Comment by prusnak** [comment]
It's about being able to run the tests on the destination machine, not maintainer's machine.

I am trying to package your work into NixOS and I have to fetch code from GitHub instead of using the official PyPI releases: see https://github.com/NixOS/nixpkgs/pull/89549

**Comment by prusnak** [comment]
I googled more on the topic and found out this comment: https://github.com/pyca/service-identity/issues/26#issuecomment-468685256

I guess we'll keep fetching the packages from GitHub, not PyPI. Sorry for the noise.
