### ISSUE TITLE
AssertionErrors are swallowed in `handle_exceptions`

### ISSUE THREAD

**Issue by alvaro-garcia-carrasco** [bcb/jsonrpcserver#135]
Whenever an `AssertionError` is raised inside a method, it is handled as an `InvalidParamsResponse` by the exception handler and the exception does not get logged ([here](https://github.com/bcb/jsonrpcserver/blob/master/jsonrpcserver/dispatcher.py#L140)). 

I have lots of assertion checks to verify the correct behaviour of the server and it becomes very difficult to debug errors raised by them.

**Comment by st31ny** [comment]
Catching the assertion error there is mainly a legacy thing there. Before we had `InvalidParamsError`, Assertions were used to signal invalid params. I guess we should get rid of that in a major release.

**Comment by bcb** [comment]
Fixed in #148
