### ISSUE TITLE
FileNotFoundError request-schema.json

### ISSUE THREAD

**Issue by BigBigXiong** [bcb/jsonrpcserver#161]
After I `pyinstaller` my python scripts, run the exe file report can't find `'C:\\Users\\XXX\\AppData\\Local\\Temp\\_MEI83882\\jsonrpcserver\\request-schema.json'`

**Comment by bcb** [comment]
This was asked in jsonrpcclient also, does it help you? https://github.com/bcb/jsonrpcclient/issues/155

**Comment by BigBigXiong** [comment]
Sorry, i meet the same error after change my `spec` file as follow
```
a = Analysis( ...
             datas=[('Lib\\site-packages\\jsonrpcserver\\request-schema.json','.')],
              ...)
```

**Comment by BigBigXiong** [comment]
Thanks @bcb ，i have solved it. 

The `spec` file write as follow:
```
a = Analysis( ...
             datas=[('Lib\\site-packages\\jsonrpcserver\\request-schema.json','jsonrpcserver')],
              ...)
```

reference: [#using-data-files-from-a-module](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#using-data-files-from-a-module)

**Comment by bcb** [comment]
I think you need to download the file from this repository and place it in the right directory.

**Comment by bcb** [comment]
Great 👍
