### ISSUE TITLE
Reverse dispatch arguments

### ISSUE THREAD

**Issue by bcb** [bcb/jsonrpcserver#26]
In order to have simpler usage (#25), should reverse the order of the `dispatch` arguments, to make the "methods" argument optional. Without methods specified, it uses the internal methods registry.

``` py
dispatch(request)
```

A breaking change..........

**Comment by spumer** [comment]
You can just add this like a shortcut, and add DeprecationWarning to standart approach ;)

**Comment by bcb** [comment]
Done in v4
