### ISSUE TITLE
Server examples should not respond to notification messages

### ISSUE THREAD

**Issue by johnkit** [bcb/jsonrpcserver#41]
The examples in the readthedocs pages show the methods/handlers responding to all requests, however, jsonrpc servers should not respond to notification requests.

**Comment by bcb** [comment]
Hi John, the server does respond to notifications in certain circumstances. For example if the request is not valid json, it can't be parsed, it's impossible to know if the request is a notification or not, so it will respond with an error.

What's the response you're getting?

**Comment by johnkit** [comment]
My point is that when a valid notification is received, the server sends a response, which it should NOT do. So, for example, your websockets example

    async def main(websocket, path):
        request = await websocket.recv()
        response = await methods.dispatch(request)
        await websocket.send(str(response))

Should be modified to something like this:

    async def main(websocket, path):
        request = await websocket.recv()
        response = await methods.dispatch(request)
        // Only respond if NOT a notification request
        if not isinstance(response, jsonrpcserver.response.NotificationResponse):
            await websocket.send(str(response))

(error handling logic not shown),

Responding to any notification request is inconsistent with the jsonrpc standard.

**Comment by bcb** [comment]
Thanks for reporting.
