### ISSUE TITLE
Change ZeroMQ documentation

### ISSUE THREAD

**Issue by tombnorwood** [bcb/jsonrpcserver#51]
Really enjoy using your library. I think you might need to update your ZeroMQ example though. In the example, you don't reply with a message if Response.is_notifcation == True. If you don't return a response, I believe this will never return a zmq.REP type socket to a readable state.

**Comment by bcb** [comment]
Well spotted, thanks

**Comment by francislavoie** [comment]
@bcb you need to also make this change on this page: https://jsonrpcserver.readthedocs.io/en/latest/examples.html#zeromq

**Comment by bcb** [comment]
Oops..... fixed that thanks @francislavoie.
