### ISSUE TITLE
Async Zmq run problem

### ISSUE THREAD

**Issue by korviinn** [bcb/jsonrpcserver#59]
Hi, I have followed your instructions from https://github.com/bcb/jsonrpcserver/blob/master/examples/aiozmq_server.py

and it's ok.

But if I try to move 
```
@methods.add
async def ping():
    return 'pong'
```

to another nearest file, jsonrpcserver can not find my ping() method.
What am I doing wrong?

Thank you in advance.

**Comment by bcb** [comment]
Is the other file being imported?

**Comment by bcb** [comment]
No response from reporter. Can't reproduce.
