### ISSUE TITLE
Use fastjsonschema instead of jsonschema

### ISSUE THREAD

**Issue by Kaveshnikov** [bcb/jsonrpcserver#82]
Hi. I was going to use this library in my asynchronous API, but JSON validation is too slow and takes up to a few seconds. It would be great if a faster library was used instead of `jsonschema`, for example, `fastjsonschema`.

**Comment by bcb** [comment]
Hmm, according to this page we're using the slowest method of validating.
https://www.peterbe.com/plog/jsonschema-validate-10x-faster-in-python

It would be 10x faster with
```python
cls = validator_for(SCHEMA)
cls.check_schema(SCHEMA)
validator = cls(SCHEMA)
validator.validate(data)
```

**Comment by Kaveshnikov** [comment]
Yes, it might work. How soon can you test the solution?

**Comment by bcb** [comment]
Won't be until the weekend. Unless you can send through a PR.

**Comment by bcb** [comment]
Made this change in version 4.0.4.

Let me know how it goes for you.

**Comment by Kaveshnikov** [comment]
RPS increased by almost twice. This is an optimal option, I can scale horizontally now. I would like a fourfold increase instead, so that I can raise a smaller number of API instances. Judging by the `сProfiler`, It is possible to increase performance by ~ 20%, if to remove the use of the `inspect` module in the validation of the function signature and in the `apply-defaults` module. I would think about it. Anyway, thanks for the help.
