### ISSUE TITLE
support multiple servers

### ISSUE THREAD

**Issue by ecdsa** [bcb/jsonrpcserver#86]
the @method decorator adds the method to a global list.
this means it is not possible to open two servers, with different RPCs, in the same python process

**Comment by okke-formsma** [comment]
You can create your own `Methods` object and then add methods to these.
```
from jsonrpcserver.methods import Methods
my_server = Methods()

@my_server.add_method
def ping(**kwargs):
    return kwargs
```

**Comment by okke-formsma** [comment]
Maybe it'd be nice to add a code example for this to the documentation?

**Comment by bcb** [comment]
Yes you're right Okke, it should be documented.

**Comment by ecdsa** [comment]
thank you. feel free to close this issue.
