### ISSUE TITLE
Be PEP 561 Compliant (add py.typed)

### ISSUE THREAD

**Issue by elihunter173** [bcb/jsonrpcserver#91]
[PEP 561] describes how libraries with type annotations should be distributed. This involves adding a marker file named `py.typed` and including it in the `setup.py`.

Currently, since this project doesn't have this, downstream projects can't easily use the type annotations provided. This should be pretty easy to add.

[PEP 561]: https://www.python.org/dev/peps/pep-0561/

**Comment by bcb** [comment]
Sounds good, I will add this.
